# Generated by Django 5.0.6 on 2024-07-24 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.CharField(default=100, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('startHour', models.TimeField()),
                ('endHour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='rtm_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_body', models.TextField()),
                ('comm_timestamp', models.DateTimeField()),
                ('comm_author', models.ForeignKey(on_delete=models.SET('N/A'), to=settings.AUTH_USER_MODEL)),
                ('comm_service', models.ForeignKey(on_delete=models.SET('N/A'), to='RTMLApp.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='working_schedule',
            field=models.ManyToManyField(to='RTMLApp.workingdays'),
        ),
    ]
