# Generated by Django 5.0.6 on 2025-07-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTMLApp', '0002_alter_rtm_comment_comm_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rap30',
            fields=[
                ('interval', models.DateTimeField(db_column='Interval', primary_key=True, serialize=False)),
                ('service', models.TextField(db_column='Service')),
                ('forecast', models.IntegerField(blank=True, db_column='Forecast', null=True)),
                ('real', models.IntegerField(blank=True, db_column='Real', null=True)),
                ('thr', models.IntegerField(blank=True, db_column='Thr', null=True)),
            ],
            options={
                'db_table': 'rap_30',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='rtm_comment',
            name='comm_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTMLApp.service'),
        ),
    ]
